[parallel_processing]
number_of_jobs = 4
cpu_batch_size = 1
gpu_batch_size = 2
max_queue_size = 100  # Increased from 1000 to 2000

[image_processing]
do_center_square_crop = false
padding = "random(40, 100)"
useEsrganModel = false
doBucketing = true
pixelart = false
pixelart_target = [512,512]
doUpscale = false
gpuid = 0

[caption_processing]
add_tags = true
shuffle_content = false
append_filename_to_captions = true
rename_output_file = true

[paths]
input_path = "P:\\datasets\\Posters"
#spandrel_model_path = "models\\2x_Loyaldk-SuperPony_500000_V2.0.pth"
spandrel_model_path = "models\\2xHFA2kAVCSRFormer_light.pth"
[llm]
use_LLM = false

[augment]
list = [
#    {type = "skip_augmentation"},
    {type = "prepend", value = "poster, ", probability = 1.0}
]

[resolutions]

target_resolutions = [
    [1152, 896], [896, 1152], [1216, 832], [832, 1216],
    [1344, 768], [768, 1344], [1536, 640], [640, 1536], [1024, 1024],
    # 512x512 equivalent resolutions
    # [512, 512], [576, 456], [456, 576], [640, 410], [410, 640],
    # [724, 362], [362, 724], [812, 323], [323, 812],
    # # 640x640 equivalent resolutions
    # [640, 640], [720, 570], [570, 720], [800, 512], [512, 800],
    # [905, 452], [452, 905], [1015, 404], [404, 1015],
    # # 768x768 equivalent resolutions
    # [768, 768], [864, 684], [684, 864], [960, 614], [614, 960],
    # [1086, 542], [542, 1086], [1218, 484], [484, 1218],
    # # 960x960 equivalent resolutions
    # [960, 960], [1080, 855], [855, 1080], [1200, 768], [768, 1200],
    # [1357, 678], [678, 1357], [1522, 605], [605, 1522]
]

#Notes
#augments:
#{ type = "prepend", value = "ohwx artstyle, ", probability = 1.0 }