[parallel_processing]
number_of_jobs = 1
batch_size = 1

[image_processing]
do_center_square_crop = false
padding = "random(80, 100)"
isEsganUpscale = false
usePilSave = false
doBucketing = true
pixelart = false
doUpscale = true
gpuid = 0

[caption_processing]
add_tags = false
shuffle_content = false
append_filename_to_captions = true
rename = true

[paths]
input_path = "P:\\datasets\\hand drawn icons"

[llm]
use_LLM = false

[augment]
list = [
    { type = "prepend", value = "ohwx artstyle, ", probability = 1.0 }
]

[resolutions]
target_resolutions = [
    [1152, 896], [896, 1152], [1216, 832], [832, 1216],
    [1344, 768], [768, 1344], [1536, 640], [640, 1536], [1024, 1024]
]
