[parallel_processing]
number_of_jobs = 12
cpu_batch_size = 1
gpu_batch_size = 1
max_queue_size = 10  # Increased from 1000 to 2000

[image_processing]
do_center_square_crop = false
padding = "random(80, 100)"
useEsrganModel = true
doBucketing = true
pixelart = false
doUpscale = true
gpuid = 0

[caption_processing]
add_tags = true
shuffle_content = false
append_filename_to_captions = true
rename_output_file = true

[paths]
input_path = "P:\\datasets\\stickers"
spandrel_model_path = "models\\2x_Loyaldk-SuperPony_500000_V2.0.pth"

[llm]
use_LLM = false

[augment]
list = [
#    {type = "skip_augmentation"},
    {type = "prepend", value = "ohwx artstyle, ", probability = 1.0}
]

[resolutions]
target_resolutions = [
    [1152, 896], [896, 1152], [1216, 832], [832, 1216],
    [1344, 768], [768, 1344], [1536, 640], [640, 1536], [1024, 1024]
]

#Notes
#augments:
#{ type = "prepend", value = "ohwx artstyle, ", probability = 1.0 }